services:
    laravel.test:
        build:
            # context: './vendor/laravel/sail/runtimes/8.3'
            context: .
            dockerfile: Dockerfile.laravel
            args:
                WWWGROUP: '${WWWGROUP}'
        # image: 'sail-8.3/app'
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        ports:
            # - '${APP_PORT:-80}:80'
            - '8000:80'
            # - '443:443'  # 追加
            - '8443:443'
            - '${VITE_PORT:-5173}:${VITE_PORT:-5173}'
        environment:
            WWWUSER: '${WWWUSER}'
            LARAVEL_SAIL: 1
            XDEBUG_MODE: '${SAIL_XDEBUG_MODE:-off}'
            XDEBUG_CONFIG: '${SAIL_XDEBUG_CONFIG:-client_host=host.docker.internal}'
            IGNITION_LOCAL_SITES_PATH: '${PWD}'
        volumes:
            - '.:/var/www/html'
            - './ssl:/etc/nginx/ssl'  # SSL証明書をマウント
            - './docker/nginx/nginx.conf:/etc/nginx/nginx.conf' 
        networks:
            - sail
        depends_on:
            - mysql
            - redis
            - python
        # command: php artisan serve --host=0.0.0.0 --port=80
    mysql:
        image: 'mysql/mysql-server:8.0'
        ports:
            - '${FORWARD_DB_PORT:-3306}:3306'
        environment:
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ROOT_HOST: '%'
            MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_USER: '${DB_USERNAME}'
            MYSQL_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ALLOW_EMPTY_PASSWORD: 1
        volumes:
            - 'sail-mysql:/var/lib/mysql'
            - './vendor/laravel/sail/database/mysql/create-testing-database.sh:/docker-entrypoint-initdb.d/10-create-testing-database.sh'
        networks:
            - sail
        healthcheck:
            test:
                - CMD
                - mysqladmin
                - ping
                - '-p${DB_PASSWORD}'
            retries: 3
            timeout: 5s
    redis:
        image: 'redis:alpine'
        ports:
            - '${FORWARD_REDIS_PORT:-6379}:6379'
        volumes:
            - 'sail-redis:/data'
        networks:
            - sail
        healthcheck:
            test:
                - CMD
                - redis-cli
                - ping
            retries: 3
            timeout: 5s
    python:
        build:
            context: ./
            dockerfile: Dockerfile.python
        ports:
            - '8080:8080'
        volumes:
            - ./app/Python:/code/app/Python
            - ./storage/app/json:/code/app/json
            - './ssl:/code/ssl'  # SSL 証明書をマウント
        environment:
            - PYTHONUNBUFFERED=1
            - ICLOUD_USERNAME=${ICLOUD_USERNAME}
            - ICLOUD_PASSWORD=${ICLOUD_PASSWORD}
        command: uvicorn app.Python.main:app --host 0.0.0.0 --port 8080 --reload --log-level debug
        networks:
            - sail
        tty: true 
networks:
    sail:
        driver: bridge
volumes:
    sail-mysql:
        driver: local
    sail-redis:
        driver: local
    sail-meilisearch:
        driver: local
